export const CALCULATIONS_LOADING = 'CALCULATIONS_LOADING';
export const CALCULATIONS_FAILED = 'CALCULATIONS_FAILED';
export const ADD_INCOME_CALCULATIONS = 'ADD_INCOME_CALCULATIONS';
export const ADD_EXPENSE_CALCULATIONS = 'ADD_EXPENSE_CALCULATIONS';